name: fx
version: 24.1.0
summary: Terminal JSON viewer
description: Terminal JSON viewer
base: core22
grade: stable
confinement: strict

apps:
  fx:
    command: fx
    plugs: [home, network]

parts:
  fx:
    plugin: go
    build-snaps:
      - go    
    source: .
